export const FRIEND_INVITATION_STATUS = {
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
} as const;

export type FRIEND_INVITATION_STATUS =
  (typeof FRIEND_INVITATION_STATUS)[keyof typeof FRIEND_INVITATION_STATUS];